const company = {
  uf: 'BA',
  cep: '41820790',
  qsa: [
    {
      pais: null,
      nome_socio: 'JANDER ALMEIDA SILVA',
      codigo_pais: null,
      faixa_etaria: 'Entre 21 a 30 anos',
      cnpj_cpf_do_socio: '***831825**',
      qualificacao_socio: 'Sócio-Administrador',
      codigo_faixa_etaria: 3,
      data_entrada_sociedade: '2021-02-09',
      identificador_de_socio: 2,
      cpf_representante_legal: '***000000**',
      nome_representante_legal: '',
      codigo_qualificacao_socio: 49,
      qualificacao_representante_legal: 'Não informada',
      codigo_qualificacao_representante_legal: 0,
    },
  ],
  cnpj: '40789236000173',
  pais: null,
  email: null,
  porte: 'MICRO EMPRESA',
  bairro: 'CAMINHO DAS ARVORES',
  numero: '1057',
  ddd_fax: '',
  municipio: 'SALVADOR',
  logradouro: 'SALVADOR',
  cnae_fiscal: 6201501,
  codigo_pais: null,
  complemento: ' SALVADOR SHOPPING BUSINESS TORRE AMERICA SALA 911 E 912',
  codigo_porte: 1,
  razao_social: 'FRONT DESENVOLVIMENTO DE PROGRAMAS LTDA',
  nome_fantasia: 'FRONT DESENVOLVIMENTO DE SISTEMAS',
  capital_social: 1000,
  ddd_telefone_1: '7199616841',
  ddd_telefone_2: '',
  opcao_pelo_mei: false,
  descricao_porte: '',
  codigo_municipio: 3849,
  cnaes_secundarios: [
    { codigo: 6201502, descricao: 'Web design' },
    { codigo: 6202300, descricao: 'Desenvolvimento e licenciamento de programas de computador customizáveis' },
    { codigo: 6203100, descricao: 'Desenvolvimento e licenciamento de programas de computador não-customizáveis' },
  ],
  natureza_juridica: 'Sociedade Empresária Limitada',
  situacao_especial: '',
  opcao_pelo_simples: true,
  situacao_cadastral: 2,
  data_opcao_pelo_mei: null,
  data_exclusao_do_mei: null,
  cnae_fiscal_descricao: 'Desenvolvimento de programas de computador sob encomenda',
  codigo_municipio_ibge: 2927408,
  data_inicio_atividade: '2021-02-09',
  data_situacao_especial: null,
  data_opcao_pelo_simples: '2021-02-09',
  data_situacao_cadastral: '2021-02-09',
  nome_cidade_no_exterior: '',
  codigo_natureza_juridica: 2062,
  data_exclusao_do_simples: null,
  motivo_situacao_cadastral: 0,
  ente_federativo_responsavel: '',
  identificador_matriz_filial: 1,
  qualificacao_do_responsavel: 49,
  descricao_situacao_cadastral: 'ATIVA',
  descricao_tipo_de_logradouro: 'ALAMEDA',
  descricao_motivo_situacao_cadastral: 'SEM MOTIVO',
  descricao_identificador_matriz_filial: 'MATRIZ',
}

export const fakeData = {
  company,
}
