export const pages = {
  companySignUp: '/cadastro-empresa',
  companySocialSignUp: '/cadastro-social-empresa',
  home: '/',
  login: '/login',
  companyProfile: '/empresas',
  ictProfile: '/icts',
  analystProfile: '/analistas',
  recoverPassword: '/recuperar-senha',
  proposal: '/proposta',
  signUp: '/cadastro',
  privacyPolicy: '/politica-de-privacidade',
  termsOfUse: '/termos-de-uso',
  confirmCode: '/confirmar-codigo',
} as const
