export const pages = {
  companyProfile: '/empresas',
  companySignUp: '/cadastro-empresa',
  confirmCode: '/confirmar-codigo',
  home: '/',
  ictProfile: '/icts',
  login: '/login',
  offer: '/oferta',
  privacyPolicy: '/politica-de-privacidade',
  proposal: '/proposta',
  recoverPassword: '/recuperar-senha',
  signUp: '/cadastro',
  termsOfUse: '/termos-de-uso',
  trls: '/trls',
  userProfile: '/usuarios',
} as const
